### ISSUE TITLE
DataLine specifics and testing

### ISSUE THREAD

**Issue by ananthamurthy** [ananthamurthy/eyeBlinkBehaviour#25]
Example dataline -->
2017-09-14T17:43:02.471696,2017-09-14T17:43:02.453811,7505,1,0,0,0,641,636,1,1,PRE_,2017-09-14T17:42:57.674862,1505391177.673743,0.000,0.000

- [x] Here, the 641 (after 7th comma) and 636 (after 8th comma) are meaningless (legacy; two IR pair based tracking). These values need not be written.

- [x] We could conserve space and also have the dataline easier to read, if we replace the last value (sign of the direction) with a string "+" (1) or "-" (2).

- [x] The pre-calculated speed (2nd last value) should be normalized to "1" not "10". This makes further calculations easier.

**Comment by dilawar** [comment]
- Leave these values there if they are harmless. Otherwise the analysis script with divert a lot between various protocols.
- Space is not a problem. We have enough width to write in the frame. However while writing text on the frame, it might fall out of the frame. Which can be fixed by reducing the fontsize.
- If sensor is r1 distance away for axis, and mouse is r2 distance away then speed is `v*r2/r1' where v is speed in cm/sec read by mouse..
